name: cui-test-keycloak-integration
pages-reference: cui-test-keycloak-integration
sonar-project-key: cuioss_cui-test-keycloak-integration
release:
  current-version: 1.0.1
  next-version: 1.1.0-SNAPSHOT
