name: cui-test-keycloak-integration
description: Simple project for integration tests using testcontainers and keycloak

release:
  current-version: 1.3.0
  next-version: 1.4.0-SNAPSHOT
  create-github-release: true

maven-build:
  java-versions: '["21","25"]'
  java-version: '21'
  enable-snapshot-deploy: true
  maven-profiles-snapshot: 'release-snapshot,javadoc'
  maven-profiles-release: 'release,javadoc'
  npm-cache: false

sonar:
  project-key: cuioss_cui-test-keycloak-integration
  enabled: true
  skip-on-dependabot: true

pages:
  reference: cui-test-keycloak-integration
  deploy-at-release: true

github-automation:
  auto-merge-build-versions: true
  auto-merge-build-timeout: 300

consumers:
  - cuioss-parent-pom:version.cui.test.keycloak.integration
  - nifi-extensions:version.cui.test.keycloak.integration

dependency-propagation:
  group-id: de.cuioss.test
  artifact-id: cui-test-keycloak-integration
  scope: dependency
